import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Weather from '../components/home/weather'
import { Suspense, useEffect, useState } from 'react'
import Cities from '../components/home/cities'
 
export default function Home() {
  const[city,setCity]=useState([]);
  
    // useEffect(() => {
     const api = async () => {
      let response = await fetch("https://countriesnow.space/api/v0.1/countries/capital/");
      if (!response.ok) {
         throw new Error(`HTTP error! status: ${response.status}`);
     }
     setCity_(await response.json())
     console.log(city)
   }
    api();

    // },[]);

   
// function cheseCity(){
//   if (process.browser) {var x=document.querySelector("#cities");
//   for (var i = 0; i < x.options.length; i++) {
//      if(x.options[i].selected ==true){
//          setCity( x.options[i].selected);
//       }}
//     }
// }

// api();    


   return (
    <div className='main_' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
<main>
  <select name="cities" id="cities" >
    {/* <Suspense fallback={"Loading..."}> */}
    {/* <Cities city={city_}/> */}
    {/* </Suspense> */}
  </select>
    <div className="weather">
      {/* <Weather city={city}/> */}
    </div>
</main>
    </div>
  )
}
