import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Weather from '../components/home/weather'
import { Suspense, useEffect, useState } from 'react'

export default function Home() {
  const [cities, setCities] = useState();

  const [city, setCity] = useState("sanaa");

  const handleClick = (name) => {
    setCity(name);
  };

  const [weather, setWeather] = useState();
// Api Of city weather
 useEffect(() => {
    fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=52922fa07c551a030f9701eff376927a`
    )
      .then((res) => res.json())
      .then((res) => {
        setWeather(res);
        console.log(weather)
      })
      .catch((err) => console.error(err));
   }, [city]);
//Api of countries capital
  useEffect(() => {
    fetch("https://countriesnow.space/api/v0.1/countries/capital/")
      .then((res) => res.json())
      .then((res) => {
        setCities(res);
      })
      .catch((err) => console.error(err));
  }, []);

  if (!cities || !weather) {
    return <div>Loading...</div>;
  }
  return (
    <div className='AllPage'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <div> <Weather onClick={handleClick} city={cities} weather={weather} /></div>
      </main>
    </div>
  );}
